### ISSUE TITLE
 Cannot use import statement outside a module

### ISSUE THREAD

**Issue by Chebattler2** [rn0x/file_size_url#1]
Hi, I get an error when I try to import this library as in example. 

import file_size_url from 'file_size_url';

![изображение](https://user-images.githubusercontent.com/98988500/160037254-26297998-1d96-471e-b7b1-efb98f4aa2c4.png)

I also tried 
var file_size_url = require('file_size_url'); 
No result. 
Tried renaming to mjs, using  "type": "module" in package.json but without success 
Nodejs version 14.15.0

**Comment by rn0x** [comment]
Delete the node_modules folder
Then ``` npm i file_size_url ```

The version nodejs I have is v16.14.0 and it works fine for me
